# Generated by Django 4.0.3 on 2022-04-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='comment',
            field=models.CharField(default='User Comments...', max_length=255),
        ),
    ]
