# Generated by Django 4.0.3 on 2022-04-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='bad',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='good',
            field=models.BooleanField(default=0),
        ),
    ]
